defaults:
  - model: mlp
  - trainer: default
  - dataset: ???  #fill this
  - _self_


# General parameters
seed: 42
max_epochs: 1000
tracked_metric: ???  # metric used for checkpoint
tracked_metric_mode: ???  # min or max
batch_size: 64
validate_only: false



# Hydra settings
hydra:
  run:
    dir: outputs/${get_fname:${model._target_}}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}